name: 'publish-action'
on: # rebuild any PRs and main branch changes
  release:
    types: [created]

jobs:
  package-and-publish: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: echosomething
        run: echo releaseid from payload is  ${{ github.event.payload.release.id }}
             echo releaseid from client payload is ${{ github.event.client_payload.release.id }}
             echo tag from payload is ${{ github.event.payload.release.tag_name }} 
             echo tag from client payload is 	${{ github.event.client_payload.release.tag_name }} 
        
      - name: Checking out!
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.payload.release.tag_name}}
        
      - name: Publish action 
        uses: actions-on-packages/package-action@0.4.1
#        with: 
#            path: 'dist/'
